---
title: "R and Stats micro-white paper"
author: "Excavating Mind"
date: "2022-11-30"
categories: ["R"]
tags: ["introduction", "r", "psychology"]
bibliography: references.bib
---

## Introduction

A psychology student's math ability is strongly associated with their quantitative research method and math performance in assignments and research. However, psychology students tend to have a lower mathematics grade than students studying the core sciences [@gibbs2010]. Additionally, students with lower mathematics grades are likely to suffer from math anxiety; the nervous feeling surrounding any learnt topic revolving around math comprehension [@zhang2019]. As numerous studies have suggested, math anxiety is strongly negatively associated with math performance [@khasawneh2021]. Lastly, psychology is becoming far more integrated with computer scientific concepts, e.g., programming in r; math and computer science ability are strongly positively associated [@sari2018]. Overall, numerous findings suggest that for psychology students to get the best out of their degrees and to truly comprehend psychological research methods, math ability must improve.

## My experience

The predominant reason for this project beginning was my own experience with mathematical concepts and psychology. I did not particularly like maths during secondary school, nor did I care for it. However, as I have continued my education and moved to postgraduate psychology, I realised several things. First, most PhD roles that I like require a strong mathematical foundation. Second, when discussing maths with my peers, most of them had a strong negative reaction to maths. Lastly, when discussing math concepts with peers throughout the last four years, few had a strong understanding of mathematics (including myself). Thus, I saw an opportunity to improve this issue.

## R and stats

Overall, I saw that if students were provided with accessible content, they could drastically improve their comprehension of difficult topics. Throughout my work as a tutor, I have constantly attempted to produce highly accessible content and provide students with every opportunity to improve their understanding. So, I thought if I could create content that my 16-year-old self would grasp, then, I would be created content that would greatly benefit other psychology students with low math understanding and high math anxiety.

## The online book

Abiding by the open science framework, the book is and always will be free to access. Currently, I am hosting the book on github pages using the bookdown package in r. [excavatingmind.github.io/RandStats/](https://excavatingmind.github.io/RandStats/ "https://excavatingmind.github.io/RandStats/")

## References
